# Mínimos Cuadrados Ordinarios (OLS) con statsmodels

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

# Datos de ejemplo
X = np.random.rand(100, 3)
y = 2 * X[:, 0] + 3 * X[:, 1] + np.random.normal(0, 0.1, 100)

# Agregar constante para el intercepto
X = sm.add_constant(X)

# Ajustar el modelo de regresión lineal
model = sm.OLS(y, X).fit()

# Resumen del modelo
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.991
Model:                            OLS   Adj. R-squared:                  0.991
Method:                 Least Squares   F-statistic:                     3693.
Date:                Tue, 29 Oct 2024   Prob (F-statistic):           5.35e-99
Time:                        14:40:28   Log-Likelihood:                 91.441
No. Observations:                 100   AIC:                            -174.9
Df Residuals:                      96   BIC:                            -164.5
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0351      0.030     -1.180      0.2

# Regresión Ridge con Scikit-learn

In [2]:
from sklearn.linear_model import Ridge

In [3]:
# Datos de ejemplo
X = np.random.rand(100, 3)
y = 2 * X[:, 0] + 3 * X[:, 1] + np.random.normal(0, 0.1, 100)

In [4]:
X.shape

(100, 3)

In [5]:
X[0:5,]

array([[0.15401252, 0.08154875, 0.57056842],
       [0.10272331, 0.1271681 , 0.39647264],
       [0.49554751, 0.25583438, 0.07730802],
       [0.07190355, 0.63342859, 0.58391351],
       [0.24885969, 0.25509151, 0.74920371]])

In [6]:
y[0:5,]

array([0.62607977, 0.50012222, 1.80760474, 2.1396964 , 1.24683956])

In [7]:
# Crear y ajustar el modelo de regresión Ridge
ridge = Ridge(alpha=1.0)
ridge.fit(X, y)

Ridge()

In [8]:
# Coeficientes del modelo
print(ridge.coef_)

[ 1.78809141  2.69159365 -0.04473341]


In [9]:
prediccion = ridge.predict(X)

In [10]:
# predicciones
prediccion[0:5,]

array([0.75372323, 0.79259008, 1.85559033, 2.0917442 , 1.38243427])

In [11]:
# valores verdaderos
y[0:5,]

array([0.62607977, 0.50012222, 1.80760474, 2.1396964 , 1.24683956])

# Regresión Lasso con Scikit-learn

In [13]:
from sklearn.linear_model import Lasso

In [14]:
# Datos de ejemplo
X = np.random.rand(100, 3)
y = 2 * X[:, 0] + 3 * X[:, 1] + np.random.normal(0, 0.1, 100)

In [15]:
# Crear y ajustar el modelo de regresión Lasso
lasso = Lasso(alpha=0.1)
lasso.fit(X, y)

Lasso(alpha=0.1)

In [16]:
# Coeficientes del modelo
print(lasso.coef_)

[ 0.79872192  1.8675801  -0.        ]


In [17]:
X[0:5,]

array([[0.54457072, 0.24589597, 0.26454939],
       [0.31758961, 0.35543652, 0.18777889],
       [0.82875312, 0.12810365, 0.66593086],
       [0.07684261, 0.30529597, 0.78749274],
       [0.82344334, 0.33055464, 0.59678845]])

In [18]:
y[0:5,]

array([1.80619501, 1.78963149, 1.99021989, 1.05316517, 2.54513116])

In [19]:
pred_lasso = lasso.predict(X)
pred_lasso[0:5,]

array([2.08049093, 2.10377191, 2.08748706, 1.8178405 , 2.46133946])

# Elastic Net con Scikit-learn

In [20]:
from sklearn.linear_model import ElasticNet

# Datos de ejemplo
X = np.random.rand(100, 3)
y = 2 * X[:, 0] + 3 * X[:, 1] + np.random.normal(0, 0.1, 100)

# Crear y ajustar el modelo de regresión Elastic Net
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.5)
elastic_net.fit(X, y)

# Coeficientes del modelo
print(elastic_net.coef_)

[1.01454007 1.56803001 0.        ]


In [21]:
pred_elastic = elastic_net.predict(X)

In [22]:
y[0:5,]

array([2.47244175, 0.92209058, 2.7086311 , 2.70546753, 4.36507018])

In [23]:
pred_elastic[0:5,]

array([2.47734183, 1.76637902, 2.61546686, 2.59963739, 3.44434897])

# Descenso del Gradiente con Scikit-learn

In [24]:
from sklearn.linear_model import SGDRegressor

# Datos de ejemplo
X = np.random.rand(100, 3)
y = 2 * X[:, 0] + 3 * X[:, 1] + np.random.normal(0, 0.1, 100)

# Crear y ajustar el modelo de regresión con descenso del gradiente
sgd = SGDRegressor(max_iter=1000, tol=1e-3)
sgd.fit(X, y)

# Coeficientes del modelo
print(sgd.coef_)

[1.06185561 1.63362267 0.24787497]


In [25]:
pred_sgd = sgd.predict(X)

In [26]:
y[0:5,]

array([1.97981786, 3.43755967, 3.49871991, 3.05589614, 1.2490044 ])

In [27]:
pred_sgd[0:5,]

array([2.39068735, 3.00290303, 3.24674632, 2.88806083, 1.80479151])