# Máquinas con Vectores de Soporte en Python

## Importación de Librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Leer los datos transformados a 8 componentes

Utilizaremos el conjunto de datos guardados del notebook anterior:

In [2]:
df = pd.read_csv("componentes_8.csv",header=None)

In [3]:
df.columns = ["CP1","CP2","CP3","CP4","CP5","CP6","CP7","CP8"]

In [4]:
df.head()

CP1        CP2       CP3       CP4       CP5       CP6       CP7  \
0  9.192837   1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159371   
1  2.387802  -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013358   
2  5.733896  -1.075174 -0.551748  0.912083 -0.177086  0.541452 -0.668167   
3  7.122953  10.275589 -3.232790  0.152547 -2.960878  3.053422  1.429910   
4  3.935302  -1.948072  1.389767  2.940639  0.546747 -1.226495 -0.936213   

        CP8  
0 -0.398407  
1  0.240988  
2  0.097374  
3  1.059566  
4  0.636376

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   CP1     569 non-null    float64
 1   CP2     569 non-null    float64
 2   CP3     569 non-null    float64
 3   CP4     569 non-null    float64
 4   CP5     569 non-null    float64
 5   CP6     569 non-null    float64
 6   CP7     569 non-null    float64
 7   CP8     569 non-null    float64
dtypes: float64(8)
memory usage: 35.7 KB


In [6]:
from sklearn.datasets import load_breast_cancer

In [7]:
#crea el diccionario de datos cancer
cancer = load_breast_cancer()

El conjunto de datos se presenta en forma de diccionario:

In [8]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

## Configuración del DataFrame

In [9]:
cancer['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [10]:
df_target = pd.DataFrame(cancer['target'],columns=['Cancer'])
df_target.head()

Cancer
0       0
1       0
2       0
3       0
4       0

In [11]:
df_target['Cancer'].value_counts()

1    357
0    212
Name: Cancer, dtype: int64

- 1 representa Benigno
- 0 Maligno

¡Ahora revisemos el dataframe!

In [12]:
#df = pd.concat([df_feat,df_target],axis=1)
df = df.join(df_target)

In [13]:
df.head()

CP1        CP2       CP3       CP4       CP5       CP6       CP7  \
0  9.192837   1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159371   
1  2.387802  -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013358   
2  5.733896  -1.075174 -0.551748  0.912083 -0.177086  0.541452 -0.668167   
3  7.122953  10.275589 -3.232790  0.152547 -2.960878  3.053422  1.429910   
4  3.935302  -1.948072  1.389767  2.940639  0.546747 -1.226495 -0.936213   

        CP8  Cancer  
0 -0.398407       0  
1  0.240988       0  
2  0.097374       0  
3  1.059566       0  
4  0.636376       0

# Análisis exploratorio de datos



Vamos a omitir esta parte, ya que hay tantas características que son difíciles de interpretar si no tiene conocimiento y dominio sobre el cáncer o las células tumorales.

# División en datos de entrenamiento y de prueba

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X = df.drop('Cancer',axis=1)

In [16]:
y = df['Cancer']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.30, 
                                                    random_state=101)

# Entrenar el clasificador con Vectores de Soporte

In [18]:
from sklearn.svm import SVC

In [19]:
model = SVC()

In [20]:
model.get_params()

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [21]:
model.fit(X_train,y_train)

SVC()

## Predicciones y evaluaciones

Ahora vamos a predecir haciendo uso del modelo entrenado.

In [22]:
predictions = model.predict(X_test)

In [23]:
from sklearn.metrics import classification_report,confusion_matrix

In [24]:
print(confusion_matrix(y_test,predictions))

[[ 63   3]
 [  1 104]]


In [25]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.98      0.95      0.97        66
           1       0.97      0.99      0.98       105

    accuracy                           0.98       171
   macro avg       0.98      0.97      0.98       171
weighted avg       0.98      0.98      0.98       171



¡Note que estamos clasificando todo en una sola clase! Esto significa que nuestro modelo necesita tener los parámetros ajustados (también puede ayudar a normalizar los datos).

¡Podemos buscar parámetros usando un GridSearch!

# Gridsearch
Encontrar los parámetros correctos (como qué valores de C o gamma usar) es una tarea difícil. Pero afortunadamente, podemos probar un montón de combinaciones y ver qué funciona mejor. Esta idea de crear una "cuadrícula" de parámetros y simplemente probar todas las combinaciones posibles se llama Gridsearch, este método es lo suficientemente común como para que Scikit-learn tenga esta funcionalidad incorporada con GridSearchCV. El CV significa validación cruzada.

GridSearchCV toma un diccionario que describe los parámetros que se deben probar y un modelo para entrenar. La cuadricula de parámetros se define como un diccionario, donde las claves son los parámetros y los valores son las configuraciones que se probarán.

In [26]:
param_grid = {'C': [0.1,1, 10, 100, 1000],
              'gamma': [1,0.1,0.01,0.001,0.0001],
              'kernel': ['rbf']} 

In [ ]:
#help(SVC)

In [27]:
from sklearn.model_selection import GridSearchCV

Una de las mejores cosas de GridSearchCV es que es un meta-estimador. Este toma un estimador como SVC, y crea un nuevo estimador, que se comporta exactamente igual, en este caso, como un clasificador. Debería agregar refit = True y elegir verbose al número que desee, más alto el número, más verboso (verboso solo significa el texto de salida que describe el proceso).

In [28]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

Lo que hace el ajuste es un poco más complicado de lo habitual. En primer lugar, ejecuta el mismo ciclo con validación cruzada, para encontrar la mejor combinación de parámetros. Una vez que tiene la mejor combinación, vuelve a funcionar con todos los datos pasados para ajustarse (sin validación cruzada), para construir un modelo nuevo usando la mejor configuración de parámetros.

In [29]:
# ¡Puede tomar un tiempo!
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.637 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.637 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.625 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.633 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.633 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.912 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.988 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.950 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.975 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.949 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.912 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

Puede inspeccionar los mejores parámetros encontrados por GridSearchCV en el atributo best_params_ y el mejor estimador en el atributo best_estimator_:

In [30]:
grid.best_params_

{'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}

In [31]:
grid.best_estimator_

SVC(C=1, gamma=0.01)

Luego puede volver a ejecutar las predicciones en este objeto grid como lo haría con un modelo normal.

In [32]:
grid_predictions = grid.predict(X_test)

In [33]:
print(confusion_matrix(y_test,grid_predictions))

[[ 58   8]
 [  1 104]]


In [34]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       0.98      0.88      0.93        66
           1       0.93      0.99      0.96       105

    accuracy                           0.95       171
   macro avg       0.96      0.93      0.94       171
weighted avg       0.95      0.95      0.95       171



# Buen trabajo!